# -*- coding: utf-8 -*-
"""flights_wrangling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FtDVIJb5XJeXuT7JhlvinV0wq4iDD7EW

# **Tópicos**

<ol type="1">
  <li>Preparação do dataset;</li>
  <li>Relatório.</li>
</ol>

---

## 1\. Motivação para o projeto

Você é o analista de dados de um grande aeroporto. O time de operações precisa acompanhar o fluxo mensal de passageiros para tomar decisões sobre manutenção, obras, etc. Você propõe a construção de um *dashboard* de dados para auxiliar o time na tomada de decisão.

## 2\. Preparação

Carregando as bibliotecas Python de manipulação de dados.
"""

import numpy as np
import pandas as pd
import seaborn as sns

"""### **2.1. Extração**

Carregando o dataset do seaborn.
"""

flights = sns.load_dataset('flights')

flights.head()

flights.tail()

flights.shape

print(f'Mínimo: {flights.year.min()}\nMáximo: {flights.year.max()}')

"""### **2.2. Transformação** """

flights.tail(1)

"""Transformando o texto da coluna `month` para sua representação numérica, exemplo: `Jan` para `1` e `Dec` para `12`."""

flights.month.drop_duplicates()

# resolução

months = {'Jan': '01',
          'Feb': '02',
          'Mar': '03',
          'Apr': '04',
          'May': '05',
          'Jun': '06',
          'Jul': '07',
          'Aug': '08',
          'Sep': '09',
          'Oct': '10',
          'Nov': '11',
          'Dec': '12'}

flights['month_new'] = flights['month'].apply(lambda month: months[month])

flights.tail(12)

"""Criando uma chave temporal `year-month` no formato `YYYY-MM` através da concatenação das colunas `year` e `month`, exemplo: `1949-01`."""

flights.info()

# resolução

flights['year'] = flights.year.astype(str)

flights['year-month'] = flights[['year','month_new']].apply('-'.join, axis=1)

flights.tail(1)

"""Reordenando as colunas da seguinte forma: `year-month`, `year`, `month` e `passengers`."""

# resolução

flights = flights[['year-month', 'year', 'month', 'passengers']]

flights.head()

"""### **2.3. Carregamento**

Trazendo o DataFrame para um arquivo com o nome `flights.csv`, no formato CSV e descartando o índice.
"""

# resolução

flights.to_csv('flights.csv', index=False)

"""- Link do dashboard no Google Data Studio.

> Link: https://datastudio.google.com/s/tash5I1TLlI

---
"""
